import type { IconType } from "react-icons";
import {
  SiReact,
  SiNodedotjs,
  SiMongodb,
  SiExpress,
  SiRedux,
  SiTailwindcss,
  SiJsonwebtokens,
  SiHtml5,
  SiCss,
  SiGit,
  SiGithub,
  SiJavascript,
  SiTypescript,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiPython,
  SiDocker,
  SiFigma,
  SiPostgresql,
  SiMysql,
  SiFirebase,
  SiGraphql,
  SiRedis,
  SiDjango,
  SiFlutter,
  SiSwift,
  SiKotlin,
  SiPhp,
  SiLaravel,
  SiWordpress,
  SiFlask,
  SiVercel,
  SiSpringboot,
  SiDotnet,
  SiSharp,
} from "react-icons/si";

// Known technology → real brand icon + brand color, purely for the
// "Technologies I Use" chips on a gig's skills (freeform text entered in the
// gig wizard). Anything not in this map falls back to a plain text badge —
// we don't guess/fabricate an icon for skills we don't recognize.
const TECH_ICON_MAP: Record<string, { icon: IconType; color: string }> = {
  react: { icon: SiReact, color: "#61DAFB" },
  "react.js": { icon: SiReact, color: "#61DAFB" },
  reactjs: { icon: SiReact, color: "#61DAFB" },
  node: { icon: SiNodedotjs, color: "#5FA04E" },
  "node.js": { icon: SiNodedotjs, color: "#5FA04E" },
  nodejs: { icon: SiNodedotjs, color: "#5FA04E" },
  mongodb: { icon: SiMongodb, color: "#00ED64" },
  mongo: { icon: SiMongodb, color: "#00ED64" },
  express: { icon: SiExpress, color: "#000000" },
  "express.js": { icon: SiExpress, color: "#000000" },
  expressjs: { icon: SiExpress, color: "#000000" },
  redux: { icon: SiRedux, color: "#764ABC" },
  tailwind: { icon: SiTailwindcss, color: "#06B6D4" },
  "tailwind css": { icon: SiTailwindcss, color: "#06B6D4" },
  tailwindcss: { icon: SiTailwindcss, color: "#06B6D4" },
  jwt: { icon: SiJsonwebtokens, color: "#000000" },
  html: { icon: SiHtml5, color: "#E34F26" },
  html5: { icon: SiHtml5, color: "#E34F26" },
  css: { icon: SiCss, color: "#1572B6" },
  css3: { icon: SiCss, color: "#1572B6" },
  git: { icon: SiGit, color: "#F05032" },
  github: { icon: SiGithub, color: "#181717" },
  javascript: { icon: SiJavascript, color: "#F7DF1E" },
  js: { icon: SiJavascript, color: "#F7DF1E" },
  typescript: { icon: SiTypescript, color: "#3178C6" },
  ts: { icon: SiTypescript, color: "#3178C6" },
  "next.js": { icon: SiNextdotjs, color: "#000000" },
  nextjs: { icon: SiNextdotjs, color: "#000000" },
  next: { icon: SiNextdotjs, color: "#000000" },
  "vue.js": { icon: SiVuedotjs, color: "#4FC08D" },
  vuejs: { icon: SiVuedotjs, color: "#4FC08D" },
  vue: { icon: SiVuedotjs, color: "#4FC08D" },
  angular: { icon: SiAngular, color: "#DD0031" },
  python: { icon: SiPython, color: "#3776AB" },
  docker: { icon: SiDocker, color: "#2496ED" },
  figma: { icon: SiFigma, color: "#F24E1E" },
  postgresql: { icon: SiPostgresql, color: "#4169E1" },
  postgres: { icon: SiPostgresql, color: "#4169E1" },
  mysql: { icon: SiMysql, color: "#4479A1" },
  firebase: { icon: SiFirebase, color: "#FFCA28" },
  graphql: { icon: SiGraphql, color: "#E10098" },
  redis: { icon: SiRedis, color: "#FF4438" },
  django: { icon: SiDjango, color: "#092E20" },
  flutter: { icon: SiFlutter, color: "#02569B" },
  swift: { icon: SiSwift, color: "#F05138" },
  kotlin: { icon: SiKotlin, color: "#7F52FF" },
  php: { icon: SiPhp, color: "#777BB4" },
  laravel: { icon: SiLaravel, color: "#FF2D20" },
  wordpress: { icon: SiWordpress, color: "#21759B" },
  flask: { icon: SiFlask, color: "#000000" },
  vercel: { icon: SiVercel, color: "#000000" },
  "spring boot": { icon: SiSpringboot, color: "#6DB33F" },
  spring: { icon: SiSpringboot, color: "#6DB33F" },
  ".net": { icon: SiDotnet, color: "#512BD4" },
  dotnet: { icon: SiDotnet, color: "#512BD4" },
  "c#": { icon: SiSharp, color: "#239120" },
  csharp: { icon: SiSharp, color: "#239120" },
};

export function getTechIcon(skill: string): { icon: IconType; color: string } | null {
  return TECH_ICON_MAP[skill.trim().toLowerCase()] ?? null;
}
